### PR TITLE
added allowUnfree back to xnode-common.nix

### PR DESCRIPTION
**Pull request by harrys522**

### CODE REVIEW

**Review by j-openmesh — CHANGES_REQUESTED** [review]
This doesn't modify allowUnfree? It appears to update the xnode_uuid and token for testing and modify the openssh enable flag (needs to be make lib.mkForce for the iso build, and lib.mkDefault for the post-boot configuration file load.

**Comment by harrys522** [comment]
> This doesn't modify allowUnfree? It appears to update the xnode_uuid and token for testing and modify the openssh enable flag (needs to be make lib.mkForce for the iso build, and lib.mkDefault for the post-boot configuration file load. It also updates the flake.lock file, which modifies dependencies - these things should each be done in a separate PR.

I changed these for testing the changes with valid creds and the mkForce disabling of openssh causes a rebuild error when trying to use that feature, but sure I can do it as 3 separate PRs.

**Comment by j-openmesh** [comment]
> > This doesn't modify allowUnfree? It appears to update the xnode_uuid and token for testing and modify the openssh enable flag (needs to be make lib.mkForce for the iso build, and lib.mkDefault for the post-boot configuration file load. It also updates the flake.lock file, which modifies dependencies - these things should each be done in a separate PR.
> 
> I changed these for testing the changes with valid creds and the mkForce disabling of openssh causes a rebuild error when trying to use that feature, but sure I can do it as 3 separate PRs.

If it needs to be changed all at once, I'll leave that up to you - esp. now, it's fine.

**Review by j-openmesh — APPROVED** [review]
:+1:

**Pull request merged**
