### PR TITLE
Wire in Openmesh core and Xnode admin packages

### PR DESCRIPTION
**Pull request by j-openmesh**
This wires in Openmesh core and Xnode admin packages so that we can integrate them into the images.

### CODE REVIEW

**Comment by j-openmesh** [comment]
Building to test and then, if good, will merge.

**Comment by j-openmesh** [comment]
Issue with services, working on it.

**Comment by j-openmesh** [comment]
Thanks, @harrys522  - good to have the admin service working in the image. Let's finish up the PR. Please review at will, and if it's good - I'll go ahead and merge.

**Comment by harrys522** [comment]
Looks good, tested iso building and confirmed that the systemd unit is included. Program arguments still need work but happy to accept this PR now.

**Pull request merged**
